name: "dl_feat_prep"

feature_definition:
  feature_type: "both" # options: "norm", "nonorm", "both".

  feature_list: [
    "ACTIVITY#RUNNING_count#4HR",
    "ACTIVITY#RUNNING_duration#4HR",
    "ACTIVITY#RUNNING_proportion#4HR",
    "ACTIVITY#ON_BICYCLE_count#4HR",
    "ACTIVITY#ON_BICYCLE_duration#4HR",
    "ACTIVITY#ON_BICYCLE_proportion#4HR",
    "ACTIVITY#IN_VEHICLE_count#4HR",
    "ACTIVITY#IN_VEHICLE_duration#4HR",
    "ACTIVITY#IN_VEHICLE_proportion#4HR",
    "ACTIVITY#WALKING_count#4HR",
    "ACTIVITY#WALKING_duration#4HR",
    "ACTIVITY#WALKING_proportion#4HR",
    "ACTIVITY#STILL_count#4HR",
    "ACTIVITY#STILL_duration#4HR",
    "ACTIVITY#STILL_proportion#4HR",
    "STEP#count#4HR",
    "STEP#count2std#4HR",
    "SIGNIFICANT_MOTION#count#4HR",
    "SIGNIFICANT_MOTION#elapsed_time#4HR",
    "GRAVITY#X_mean#4HR",
    "GRAVITY#X_min#4HR",
    "GRAVITY#X_max#4HR",
    "GRAVITY#X_std#4HR",
    "GRAVITY#X_kurtosis#4HR",
    "GRAVITY#X_skewness#4HR",
    "GRAVITY#Y_mean#4HR",
    "GRAVITY#Y_min#4HR",
    "GRAVITY#Y_max#4HR",
    "GRAVITY#Y_std#4HR",
    "GRAVITY#Y_kurtosis#4HR",
    "GRAVITY#Y_skewness#4HR",
    "GRAVITY#Z_mean#4HR",
    "GRAVITY#Z_min#4HR",
    "GRAVITY#Z_max#4HR",
    "GRAVITY#Z_std#4HR",
    "GRAVITY#Z_kurtosis#4HR",
    "GRAVITY#Z_skewness#4HR",
    "LIGHT#count_0#4HR",
    "LIGHT#BRIGHTNESS_LOG_mean#4HR",
    "LIGHT#BRIGHTNESS_LOG_min#4HR",
    "LIGHT#BRIGHTNESS_LOG_max#4HR",
    "LIGHT#BRIGHTNESS_LOG_std#4HR",
    "LIGHT#BRIGHTNESS_LOG_kurtosis#4HR",
    "LIGHT#BRIGHTNESS_LOG_skewness#4HR",
    "APPUSAGE#entropy#4HR",
    "APPUSAGE#normalized_entropy#4HR",
    "APPUSAGE#COMMUNICATION_count#4HR",
    "APPUSAGE#COMMUNICATION_duration#4HR",
    "APPUSAGE#SOCIAL_count#4HR",
    "APPUSAGE#SOCIAL_duration#4HR",
    "APPUSAGE#HEALTH_count#4HR",
    "APPUSAGE#HEALTH_duration#4HR",
    "APPUSAGE#ENTERTAINMENT_count#4HR",
    "APPUSAGE#ENTERTAINMENT_duration#4HR",
    "APPUSAGE#LIFESTYLE_count#4HR",
    "APPUSAGE#LIFESTYLE_duration#4HR",
    "APPUSAGE#BOOKS_count#4HR",
    "APPUSAGE#BOOKS_duration#4HR",
    "APPUSAGE#VIDEO_count#4HR",
    "APPUSAGE#VIDEO_duration#4HR",
    "APPUSAGE#FINANCE_count#4HR",
    "APPUSAGE#FINANCE_duration#4HR",
    "APPUSAGE#PHOTOGRAPHY_count#4HR",
    "APPUSAGE#PHOTOGRAPHY_duration#4HR",
    "APPUSAGE#PRODUCTIVITY_count#4HR",
    "APPUSAGE#PRODUCTIVITY_duration#4HR",
    "CALL#count_ratio_in2missed#4HR",
    "CALL#count_ratio_in2out#4HR",
    "CALL#duration_ratio_in2out#4HR",
    "CALL#IN_duration#4HR",
    "CALL#OUT_duration#4HR",
    "CALL#MISSED_count#4HR",
    "CALL#IN_count#4HR",
    "CALL#OUT_count#4HR",
    "EMA#sleep_trouble#4HR",
    "EMA#poor_appetite#4HR",
    "KEYSTROKE#SOCIAL_backspace_ratio#4HR",
    "KEYSTROKE#SOCIAL_autocorrect_ratio#4HR",
    "KEYSTROKE#SOCIAL_autocorrect_accept_ratio#4HR",
    "KEYSTROKE#SOCIAL_count_sessions#4HR",
    "KEYSTROKE#SOCIAL_interkeyDelay_mean#4HR",
    "KEYSTROKE#NON-SOCIAL_backspace_ratio#4HR",
    "KEYSTROKE#NON-SOCIAL_autocorrect_ratio#4HR",
    "KEYSTROKE#NON-SOCIAL_autocorrect_accept_ratio#4HR",
    "KEYSTROKE#NON-SOCIAL_count_sessions#4HR",
    "KEYSTROKE#NON-SOCIAL_interkeyDelay_mean#4HR",
    "NOTIFICATIONS#SOCIAL_ARRIVED_count#4HR",
    "NOTIFICATIONS#SOCIAL_CLICKED_count#4HR",
    "NOTIFICATIONS#SOCIAL_DECISION_TIME_count#4HR",
    "NOTIFICATIONS#SOCIAL_DECISION_TIME_duration_in_sec#4HR",
    "NOTIFICATIONS#SOCIAL_count_ratio_clicked2arrived#4HR",
    "NOTIFICATIONS#SOCIAL_count_ratio_decided2arrived#4HR",
    "NOTIFICATIONS#NON-SOCIAL_ARRIVED_count#4HR",
    "NOTIFICATIONS#NON-SOCIAL_CLICKED_count#4HR",
    "NOTIFICATIONS#NON-SOCIAL_DECISION_TIME_count#4HR",
    "NOTIFICATIONS#NON-SOCIAL_DECISION_TIME_duration_in_sec#4HR",
    "NOTIFICATIONS#NON-SOCIAL_count_ratio_clicked2arrived#4HR",
    "NOTIFICATIONS#NON-SOCIAL_count_ratio_decided2arrived#4HR",
    "SCREEN_STATE#on_count#4HR",
    "SCREEN_STATE#off_count#4HR",
    "SCREEN_STATE#entropy#4HR",
    "SCREEN_STATE#normalized_entropy#4HR",
    "SCREEN_STATE#total_duration#4HR",
    "SCREEN_STATE#mean_duration#4HR",
    "SCREEN_STATE#check_count#4HR",
    "SOUND#ENERGY_mean#4HR",
    "SOUND#ENERGY_min#4HR",
    "SOUND#ENERGY_max#4HR",
    "SOUND#ENERGY_std#4HR",
    "SOUND#ENERGY_kurtosis#4HR",
    "SOUND#ENERGY_skewness#4HR",
    "TYPING#SOCIAL_count#4HR",
    "TYPING#SOCIAL_total#4HR",
    "TYPING#SOCIAL_mean#4HR",
    "TYPING#SOCIAL_std#4HR",
    "TYPING#SOCIAL_min#4HR",
    "TYPING#SOCIAL_max#4HR",
    "TYPING#SOCIAL_kurtosis#4HR",
    "TYPING#SOCIAL_skewness#4HR",
    "TYPING#NON-SOCIAL_count#4HR",
    "TYPING#NON-SOCIAL_total#4HR",
    "TYPING#NON-SOCIAL_mean#4HR",
    "TYPING#NON-SOCIAL_std#4HR",
    "TYPING#NON-SOCIAL_min#4HR",
    "TYPING#NON-SOCIAL_max#4HR",
    "TYPING#NON-SOCIAL_kurtosis#4HR",
    "TYPING#NON-SOCIAL_skewness#4HR",
    "UNLOCK_STATE#unlock_count#4HR",
    "UNLOCK_STATE#lock_count#4HR",
    "UNLOCK_STATE#entropy#4HR",
    "UNLOCK_STATE#normalized_entropy#4HR",
    "UNLOCK_STATE#total_duration#4HR",
    "UNLOCK_STATE#mean_duration#4HR",
  ]
  # """
  # feature_list: [
  #           "f_screen:phone_screen_rapids_countepisodeunlock_locmap_exercise:afternoon",
  #           "f_screen:phone_screen_rapids_countepisodeunlock_locmap_greens:night",
  #           "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_exercise:allday",
  #           "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_exercise:night",
  #           "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_home:night",
  #           "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise:evening",
  #           "f_screen:phone_screen_rapids_maxdurationunlock_locmap_greens:allday",
  #           "f_screen:phone_screen_rapids_maxdurationunlock_locmap_greens:night",
  #           "f_screen:phone_screen_rapids_maxdurationunlock_locmap_home:night",
  #           "f_screen:phone_screen_rapids_maxdurationunlock_locmap_study:evening",
  #           "f_screen:phone_screen_rapids_mindurationunlock_locmap_exercise:evening",
  #           "f_screen:phone_screen_rapids_mindurationunlock_locmap_exercise:morning",
  #           "f_screen:phone_screen_rapids_stddurationunlock_locmap_exercise:evening",
  #           "f_screen:phone_screen_rapids_stddurationunlock_locmap_home:night",
  #           "f_screen:phone_screen_rapids_sumdurationunlock_locmap_exercise:night",
  #           "f_screen:phone_screen_rapids_sumdurationunlock_locmap_home:night",
  #           "f_screen:phone_screen_rapids_sumdurationunlock_locmap_living:night",
  #           "f_slp:fitbit_sleep_intraday_rapids_maxdurationasleepunifiedmain:night",
  #           "f_slp:fitbit_sleep_intraday_rapids_maxdurationawakeunifiedmain:night",
  #           "f_slp:fitbit_sleep_intraday_rapids_mindurationasleepunifiedmain:afternoon",
  #           "f_slp:fitbit_sleep_intraday_rapids_mindurationasleepunifiedmain:night",
  #           "f_slp:fitbit_sleep_intraday_rapids_sumdurationasleepunifiedmain:allday",
  #           "f_slp:fitbit_sleep_summary_rapids_avgdurationasleepmain:allday",
  #           "f_slp:fitbit_sleep_summary_rapids_avgdurationinbedmain:allday",
  #           "f_slp:fitbit_sleep_summary_rapids_lastbedtimemain:allday",
  #           "f_slp:fitbit_sleep_summary_rapids_sumdurationasleepmain:allday",
  #           "f_slp:fitbit_sleep_summary_rapids_sumdurationinbedmain:allday",
  #           "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout:evening",
  #           "f_steps:fitbit_steps_intraday_rapids_maxdurationactivebout:morning",
  #           "f_steps:fitbit_steps_intraday_rapids_maxsteps:evening",
  #           "f_steps:fitbit_steps_intraday_rapids_mindurationactivebout:evening",

  #           "f_loc:phone_locations_doryab_locationentropy_norm:afternoon",
  #           "f_loc:phone_locations_doryab_loglocationvariance_norm:allday",
  #           "f_loc:phone_locations_doryab_minlengthstayatclusters_norm:afternoon",
  #           "f_loc:phone_locations_doryab_outlierstimepercent_norm:morning",
  #           "f_loc:phone_locations_doryab_radiusgyration_norm:allday",
  #           "f_screen:phone_screen_rapids_avgdurationunlock_locmap_exercise_norm:evening",
  #           "f_screen:phone_screen_rapids_avgdurationunlock_locmap_greens_norm:night",
  #           "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_exercise_norm:allday",
  #           "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise_norm:afternoon",
  #           "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise_norm:evening",
  #           "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise_norm:night",
  #           "f_screen:phone_screen_rapids_maxdurationunlock_locmap_greens_norm:evening",
  #           "f_screen:phone_screen_rapids_sumdurationunlock_locmap_home_norm:morning",
  #           "f_slp:fitbit_sleep_intraday_rapids_maxdurationawakeunifiedmain_norm:afternoon",
  #           "f_slp:fitbit_sleep_intraday_rapids_ratiodurationasleepunifiedwithinmain_norm:afternoon",
  #           "f_slp:fitbit_sleep_intraday_rapids_ratiodurationawakeunifiedwithinmain_norm:afternoon",
  #           "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout_norm:afternoon",
  #           "f_steps:fitbit_steps_intraday_rapids_maxdurationsedentarybout_norm:night",
  #           "f_steps:fitbit_steps_intraday_rapids_stdsteps_norm:morning",
  #       ]"""

  feature_list_more_feat_types: [
    "ACTIVITY#RUNNING_count#4HR",
    "ACTIVITY#RUNNING_duration#4HR",
    "ACTIVITY#RUNNING_proportion#4HR",
    "ACTIVITY#ON_BICYCLE_count#4HR",
    "ACTIVITY#ON_BICYCLE_duration#4HR",
    "ACTIVITY#ON_BICYCLE_proportion#4HR",
    "ACTIVITY#IN_VEHICLE_count#4HR",
    "ACTIVITY#IN_VEHICLE_duration#4HR",
    "ACTIVITY#IN_VEHICLE_proportion#4HR",
    "ACTIVITY#WALKING_count#4HR",
    "ACTIVITY#WALKING_duration#4HR",
    "ACTIVITY#WALKING_proportion#4HR",
    "ACTIVITY#STILL_count#4HR",
    "ACTIVITY#STILL_duration#4HR",
    "ACTIVITY#STILL_proportion#4HR",
    "STEP#count#4HR",
    "STEP#count2std#4HR",
    "SIGNIFICANT_MOTION#count#4HR",
    "SIGNIFICANT_MOTION#elapsed_time#4HR",
    "GRAVITY#X_mean#4HR",
    "GRAVITY#X_min#4HR",
    "GRAVITY#X_max#4HR",
    "GRAVITY#X_std#4HR",
    "GRAVITY#X_kurtosis#4HR",
    "GRAVITY#X_skewness#4HR",
    "GRAVITY#Y_mean#4HR",
    "GRAVITY#Y_min#4HR",
    "GRAVITY#Y_max#4HR",
    "GRAVITY#Y_std#4HR",
    "GRAVITY#Y_kurtosis#4HR",
    "GRAVITY#Y_skewness#4HR",
    "GRAVITY#Z_mean#4HR",
    "GRAVITY#Z_min#4HR",
    "GRAVITY#Z_max#4HR",
    "GRAVITY#Z_std#4HR",
    "GRAVITY#Z_kurtosis#4HR",
    "GRAVITY#Z_skewness#4HR",
    "LIGHT#count_0#4HR",
    "LIGHT#BRIGHTNESS_LOG_mean#4HR",
    "LIGHT#BRIGHTNESS_LOG_min#4HR",
    "LIGHT#BRIGHTNESS_LOG_max#4HR",
    "LIGHT#BRIGHTNESS_LOG_std#4HR",
    "LIGHT#BRIGHTNESS_LOG_kurtosis#4HR",
    "LIGHT#BRIGHTNESS_LOG_skewness#4HR",
    "APPUSAGE#entropy#4HR",
    "APPUSAGE#normalized_entropy#4HR",
    "APPUSAGE#COMMUNICATION#count#4HR",
    "APPUSAGE#COMMUNICATION#duration#4HR",
    "APPUSAGE#SOCIAL#count#4HR",
    "APPUSAGE#SOCIAL#duration#4HR",
    "APPUSAGE#HEALTH#count#4HR",
    "APPUSAGE#HEALTH#duration#4HR",
    "APPUSAGE#ENTERTAINMENT#count#4HR",
    "APPUSAGE#ENTERTAINMENT#duration#4HR",
    "APPUSAGE#LIFESTYLE#count#4HR",
    "APPUSAGE#LIFESTYLE#duration#4HR",
    "APPUSAGE#BOOKS#count#4HR",
    "APPUSAGE#BOOKS#duration#4HR",
    "APPUSAGE#VIDEO#count#4HR",
    "APPUSAGE#VIDEO#duration#4HR",
    "APPUSAGE#FINANCE#count#4HR",
    "APPUSAGE#FINANCE#duration#4HR",
    "APPUSAGE#PHOTOGRAPHY#count#4HR",
    "APPUSAGE#PHOTOGRAPHY#duration#4HR",
    "APPUSAGE#PRODUCTIVITY#count#4HR",
    "APPUSAGE#PRODUCTIVITY#duration#4HR",
    "CALL#count_ratio_in2missed#4HR",
    "CALL#count_ratio_in2out#4HR",
    "CALL#duration_ratio_in2out#4HR",
    "CALL#IN_duration#4HR",
    "CALL#OUT_duration#4HR",
    "CALL#MISSED_count#4HR",
    "CALL#IN_count#4HR",
    "CALL#OUT_count#4HR",
    #"EMA#sleep_trouble#4HR",
    #"EMA#poor_appetite#4HR",
    "KEYSTROKE#SOCIAL#backspace_ratio#4HR",
    "KEYSTROKE#SOCIAL#autocorrect_ratio#4HR",
    "KEYSTROKE#SOCIAL#autocorrect_accept_ratio#4HR",
    "KEYSTROKE#SOCIAL#count_sessions#4HR",
    "KEYSTROKE#SOCIAL#interkeyDelay#mean",
    "KEYSTROKE#NON-SOCIAL#backspace_ratio#4HR",
    "KEYSTROKE#NON-SOCIAL#autocorrect_ratio#4HR",
    "KEYSTROKE#NON-SOCIAL#autocorrect_accept_ratio#4HR",
    "KEYSTROKE#NON-SOCIAL#count_sessions#4HR",
    "KEYSTROKE#NON-SOCIAL#interkeyDelay#mean",
    "NOTIFICATIONS#SOCIAL#ARRIVED_count#4HR",
    "NOTIFICATIONS#SOCIAL#CLICKED_count#4HR",
    "NOTIFICATIONS#SOCIAL#DECISION_TIME_count#4HR",
    "NOTIFICATIONS#SOCIAL#DECISION_TIME_duration_in_sec",
    "NOTIFICATIONS#SOCIAL#count_ratio_clicked2arrived#4HR",
    "NOTIFICATIONS#SOCIAL#count_ratio_decided2arrived#4HR",
    "NOTIFICATIONS#NON-SOCIAL#ARRIVED_count#4HR",
    "NOTIFICATIONS#NON-SOCIAL#CLICKED_count#4HR",
    "NOTIFICATIONS#NON-SOCIAL#DECISION_TIME_count#4HR",
    "NOTIFICATIONS#NON-SOCIAL#DECISION_TIME_duration_in_sec",
    "NOTIFICATIONS#NON-SOCIAL#count_ratio_clicked2arrived#4HR",
    "NOTIFICATIONS#NON-SOCIAL#count_ratio_decided2arrived#4HR",
    "SCREEN_STATE#on_count#4HR",
    "SCREEN_STATE#off_count#4HR",
    "SCREEN_STATE#entropy#4HR",
    "SCREEN_STATE#normalized_entropy#4HR",
    "SCREEN_STATE#total_duration#4HR",
    "SCREEN_STATE#mean_duration#4HR",
    "SCREEN_STATE#check_count#4HR",
    "SOUND#ENERGY_mean#4HR",
    "SOUND#ENERGY_min#4HR",
    "SOUND#ENERGY_max#4HR",
    "SOUND#ENERGY_std#4HR",
    "SOUND#ENERGY_kurtosis#4HR",
    "SOUND#ENERGY_skewness#4HR",
    "TYPING#SOCIAL#count#4HR",
    "TYPING#SOCIAL#total#4HR",
    "TYPING#SOCIAL#mean#4HR",
    "TYPING#SOCIAL#std#4HR",
    "TYPING#SOCIAL#min#4HR",
    "TYPING#SOCIAL#max#4HR",
    "TYPING#SOCIAL#kurtosis#4HR",
    "TYPING#SOCIAL#skewness#4HR",
    "TYPING#NON-SOCIAL#count#4HR",
    "TYPING#NON-SOCIAL#total#4HR",
    "TYPING#NON-SOCIAL#mean#4HR",
    "TYPING#NON-SOCIAL#std#4HR",
    "TYPING#NON-SOCIAL#min#4HR",
    "TYPING#NON-SOCIAL#max#4HR",
    "TYPING#NON-SOCIAL#kurtosis#4HR",
    "TYPING#NON-SOCIAL#skewness#4HR",
    "UNLOCK_STATE#unlock_count#4HR",
    "UNLOCK_STATE#lock_count#4HR",
    "UNLOCK_STATE#entropy#4HR",
    "UNLOCK_STATE#normalized_entropy#4HR",
    "UNLOCK_STATE#total_duration#4HR",
    "UNLOCK_STATE#mean_duration#4HR",
  ]


  # feature_list_more_feat_types: [
  #           "f_screen:phone_screen_rapids_countepisodeunlock_locmap_exercise:afternoon",
  #           "f_screen:phone_screen_rapids_countepisodeunlock_locmap_greens:night",
  #           "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_exercise:allday",
  #           "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_exercise:night",
  #           "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_home:night",
  #           "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise:evening",
  #           "f_screen:phone_screen_rapids_maxdurationunlock_locmap_greens:allday",
  #           "f_screen:phone_screen_rapids_maxdurationunlock_locmap_greens:night",
  #           "f_screen:phone_screen_rapids_maxdurationunlock_locmap_home:night",
  #           "f_screen:phone_screen_rapids_maxdurationunlock_locmap_study:evening",
  #           "f_screen:phone_screen_rapids_mindurationunlock_locmap_exercise:evening",
  #           "f_screen:phone_screen_rapids_mindurationunlock_locmap_exercise:morning",
  #           "f_screen:phone_screen_rapids_stddurationunlock_locmap_exercise:evening",
  #           "f_screen:phone_screen_rapids_stddurationunlock_locmap_home:night",
  #           "f_screen:phone_screen_rapids_sumdurationunlock_locmap_exercise:night",
  #           "f_screen:phone_screen_rapids_sumdurationunlock_locmap_home:night",
  #           "f_screen:phone_screen_rapids_sumdurationunlock_locmap_living:night",
  #           "f_slp:fitbit_sleep_intraday_rapids_maxdurationasleepunifiedmain:night",
  #           "f_slp:fitbit_sleep_intraday_rapids_maxdurationawakeunifiedmain:night",
  #           "f_slp:fitbit_sleep_intraday_rapids_mindurationasleepunifiedmain:afternoon",
  #           "f_slp:fitbit_sleep_intraday_rapids_mindurationasleepunifiedmain:night",
  #           "f_slp:fitbit_sleep_intraday_rapids_sumdurationasleepunifiedmain:allday",
  #           "f_slp:fitbit_sleep_summary_rapids_avgdurationasleepmain:allday",
  #           "f_slp:fitbit_sleep_summary_rapids_avgdurationinbedmain:allday",
  #           "f_slp:fitbit_sleep_summary_rapids_lastbedtimemain:allday",
  #           "f_slp:fitbit_sleep_summary_rapids_sumdurationasleepmain:allday",
  #           "f_slp:fitbit_sleep_summary_rapids_sumdurationinbedmain:allday",
  #           "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout:evening",
  #           "f_steps:fitbit_steps_intraday_rapids_maxdurationactivebout:morning",
  #           "f_steps:fitbit_steps_intraday_rapids_maxsteps:evening",
  #           "f_steps:fitbit_steps_intraday_rapids_mindurationactivebout:evening",
  #           "f_blue:phone_bluetooth_doryab_uniquedevicesown:night",
  #           "f_call:phone_calls_rapids_incoming_distinctcontacts:afternoon",

  #           "f_loc:phone_locations_doryab_locationentropy_norm:afternoon",
  #           "f_loc:phone_locations_doryab_loglocationvariance_norm:allday",
  #           "f_loc:phone_locations_doryab_minlengthstayatclusters_norm:afternoon",
  #           "f_loc:phone_locations_doryab_outlierstimepercent_norm:morning",
  #           "f_loc:phone_locations_doryab_radiusgyration_norm:allday",
  #           "f_screen:phone_screen_rapids_avgdurationunlock_locmap_exercise_norm:evening",
  #           "f_screen:phone_screen_rapids_avgdurationunlock_locmap_greens_norm:night",
  #           "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_exercise_norm:allday",
  #           "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise_norm:afternoon",
  #           "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise_norm:evening",
  #           "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise_norm:night",
  #           "f_screen:phone_screen_rapids_maxdurationunlock_locmap_greens_norm:evening",
  #           "f_screen:phone_screen_rapids_sumdurationunlock_locmap_home_norm:morning",
  #           "f_slp:fitbit_sleep_intraday_rapids_maxdurationawakeunifiedmain_norm:afternoon",
  #           "f_slp:fitbit_sleep_intraday_rapids_ratiodurationasleepunifiedwithinmain_norm:afternoon",
  #           "f_slp:fitbit_sleep_intraday_rapids_ratiodurationawakeunifiedwithinmain_norm:afternoon",
  #           "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout_norm:afternoon",
  #           "f_steps:fitbit_steps_intraday_rapids_maxdurationsedentarybout_norm:night",
  #           "f_steps:fitbit_steps_intraday_rapids_stdsteps_norm:morning",
  #           "f_blue:phone_bluetooth_doryab_countscansmostfrequentdeviceacrossdatasetown_norm:night",
  #           "f_call:phone_calls_rapids_outgoing_count_norm:afternoon",
        # ]

