name: "ml_xu_interpretable"

feature_definition:
  use_norm_features: False # whether to use normalized features
  empty_feature_filtering_th: 0.5 # remove features based on a threshold
  include_device_type: False # whether to include device type in the feature matrix
  # Feature used in the paper (a subset that is compatible within the dataset)

  feature_list_base: [
    "ACTIVITY#RUNNING_count#4HR",
    "ACTIVITY#RUNNING_duration#4HR",
    "ACTIVITY#RUNNING_proportion#4HR",
    "ACTIVITY#ON_BICYCLE_count#4HR",
    "ACTIVITY#ON_BICYCLE_duration#4HR",
    "ACTIVITY#ON_BICYCLE_proportion#4HR",
    "ACTIVITY#IN_VEHICLE_count#4HR",
    "ACTIVITY#IN_VEHICLE_duration#4HR",
    "ACTIVITY#IN_VEHICLE_proportion#4HR",
    "ACTIVITY#WALKING_count#4HR",
    "ACTIVITY#WALKING_duration#4HR",
    "ACTIVITY#WALKING_proportion#4HR",
    "ACTIVITY#STILL_count#4HR",
    "ACTIVITY#STILL_duration#4HR",
    "ACTIVITY#STILL_proportion#4HR",
    
    "STEP#count#4HR",
    #"STEP#count2std#4HR",
    
    "SIGNIFICANT_MOTION#count#4HR",
    #"SIGNIFICANT_MOTION#elapsed_time#4HR",
    
    # "GRAVITY#X_mean#4HR",
    # "GRAVITY#X_min#4HR",
    # "GRAVITY#X_max#4HR",
    "GRAVITY#X_std#4HR",
    # "GRAVITY#X_kurtosis#4HR",
    # "GRAVITY#X_skewness#4HR",
    # "GRAVITY#Y_mean#4HR",
    # "GRAVITY#Y_min#4HR",
    # "GRAVITY#Y_max#4HR",
    "GRAVITY#Y_std#4HR",
    # "GRAVITY#Y_kurtosis#4HR",
    # "GRAVITY#Y_skewness#4HR",
    # "GRAVITY#Z_mean#4HR",
    # "GRAVITY#Z_min#4HR",
    # "GRAVITY#Z_max#4HR",
    "GRAVITY#Z_std#4HR",
    # "GRAVITY#Z_kurtosis#4HR",
    # "GRAVITY#Z_skewness#4HR",

    "LIGHT#count_0#4HR",
    "LIGHT#BRIGHTNESS_LOG_mean#4HR",
    # "LIGHT#BRIGHTNESS_LOG_min#4HR",
    # "LIGHT#BRIGHTNESS_LOG_max#4HR",
    "LIGHT#BRIGHTNESS_LOG_std#4HR",
    # "LIGHT#BRIGHTNESS_LOG_kurtosis#4HR",
    # "LIGHT#BRIGHTNESS_LOG_skewness#4HR",

    # "APPUSAGE#entropy#4HR",
    # "APPUSAGE#normalized_entropy#4HR",
    "APPUSAGE#COMMUNICATION_count#4HR",
    "APPUSAGE#COMMUNICATION_duration#4HR",
    "APPUSAGE#SOCIAL_count#4HR",
    "APPUSAGE#SOCIAL_duration#4HR",
    "APPUSAGE#HEALTH_count#4HR",
    "APPUSAGE#HEALTH_duration#4HR",
    "APPUSAGE#ENTERTAINMENT_count#4HR",
    "APPUSAGE#ENTERTAINMENT_duration#4HR",
    "APPUSAGE#LIFESTYLE_count#4HR",
    "APPUSAGE#LIFESTYLE_duration#4HR",
    "APPUSAGE#BOOKS_count#4HR",
    "APPUSAGE#BOOKS_duration#4HR",
    "APPUSAGE#VIDEO_count#4HR",
    "APPUSAGE#VIDEO_duration#4HR",
    "APPUSAGE#FINANCE_count#4HR",
    "APPUSAGE#FINANCE_duration#4HR",
    "APPUSAGE#PHOTOGRAPHY_count#4HR",
    "APPUSAGE#PHOTOGRAPHY_duration#4HR",
    "APPUSAGE#PRODUCTIVITY_count#4HR",
    "APPUSAGE#PRODUCTIVITY_duration#4HR",
    
    "CALL#count_ratio_in2missed#4HR",
    "CALL#count_ratio_in2out#4HR",
    "CALL#duration_ratio_in2out#4HR",
    "CALL#IN_duration#4HR",
    "CALL#OUT_duration#4HR",
    "CALL#MISSED_count#4HR",
    "CALL#IN_count#4HR",
    "CALL#OUT_count#4HR",

    # "EMA#sleep_trouble#4HR",
    # "EMA#poor_appetite#4HR",

    "KEYSTROKE#SOCIAL_backspace_ratio#4HR",
    "KEYSTROKE#SOCIAL_autocorrect_ratio#4HR",
    "KEYSTROKE#SOCIAL_autocorrect_accept_ratio#4HR",
    "KEYSTROKE#SOCIAL_count_sessions#4HR",
    "KEYSTROKE#SOCIAL_interkeyDelay_mean#4HR",
    "KEYSTROKE#NON-SOCIAL_backspace_ratio#4HR",
    "KEYSTROKE#NON-SOCIAL_autocorrect_ratio#4HR",
    "KEYSTROKE#NON-SOCIAL_autocorrect_accept_ratio#4HR",
    "KEYSTROKE#NON-SOCIAL_count_sessions#4HR",
    "KEYSTROKE#NON-SOCIAL_interkeyDelay_mean#4HR",

    "NOTIFICATIONS#SOCIAL_ARRIVED_count#4HR",
    "NOTIFICATIONS#SOCIAL_CLICKED_count#4HR",
    "NOTIFICATIONS#SOCIAL_DECISION_TIME_count#4HR",
    "NOTIFICATIONS#SOCIAL_DECISION_TIME_duration_in_sec#4HR",
    "NOTIFICATIONS#SOCIAL_count_ratio_clicked2arrived#4HR",
    "NOTIFICATIONS#SOCIAL_count_ratio_decided2arrived#4HR",
    "NOTIFICATIONS#NON-SOCIAL_ARRIVED_count#4HR",
    "NOTIFICATIONS#NON-SOCIAL_CLICKED_count#4HR",
    "NOTIFICATIONS#NON-SOCIAL_DECISION_TIME_count#4HR",
    "NOTIFICATIONS#NON-SOCIAL_DECISION_TIME_duration_in_sec#4HR",
    "NOTIFICATIONS#NON-SOCIAL_count_ratio_clicked2arrived#4HR",
    "NOTIFICATIONS#NON-SOCIAL_count_ratio_decided2arrived#4HR",

    "SCREEN_STATE#on_count#4HR",
    # "SCREEN_STATE#off_count#4HR",
    # "SCREEN_STATE#entropy#4HR",
    # "SCREEN_STATE#normalized_entropy#4HR",
    "SCREEN_STATE#total_duration#4HR",
    # "SCREEN_STATE#mean_duration#4HR",
    "SCREEN_STATE#check_count#4HR",

    "SOUND#ENERGY_mean#4HR",
    # "SOUND#ENERGY_min#4HR",
    # "SOUND#ENERGY_max#4HR",
    "SOUND#ENERGY_std#4HR",
    # "SOUND#ENERGY_kurtosis#4HR",
    # "SOUND#ENERGY_skewness#4HR",

    "TYPING#SOCIAL_count#4HR",
    "TYPING#SOCIAL_total#4HR",
    # "TYPING#SOCIAL_mean#4HR",
    # "TYPING#SOCIAL_std#4HR",
    # "TYPING#SOCIAL_min#4HR",
    # "TYPING#SOCIAL_max#4HR",
    # "TYPING#SOCIAL_kurtosis#4HR",
    # "TYPING#SOCIAL_skewness#4HR",
    "TYPING#NON-SOCIAL_count#4HR",
    "TYPING#NON-SOCIAL_total#4HR",
    # "TYPING#NON-SOCIAL_mean#4HR",
    # "TYPING#NON-SOCIAL_std#4HR",
    # "TYPING#NON-SOCIAL_min#4HR",
    # "TYPING#NON-SOCIAL_max#4HR",
    # "TYPING#NON-SOCIAL_kurtosis#4HR",
    # "TYPING#NON-SOCIAL_skewness#4HR",

    "UNLOCK_STATE#unlock_count#4HR",
    # "UNLOCK_STATE#lock_count#4HR",
    # "UNLOCK_STATE#entropy#4HR",
    # "UNLOCK_STATE#normalized_entropy#4HR",
    "UNLOCK_STATE#total_duration#4HR",
    # "UNLOCK_STATE#mean_duration#4HR",
  ]

  feature_list_more_feat_types_base: [
    "ACTIVITY#RUNNING_count#4HR",
    "ACTIVITY#RUNNING_duration#4HR",
    "ACTIVITY#RUNNING_proportion#4HR",
    "ACTIVITY#ON_BICYCLE_count#4HR",
    "ACTIVITY#ON_BICYCLE_duration#4HR",
    "ACTIVITY#ON_BICYCLE_proportion#4HR",
    "ACTIVITY#IN_VEHICLE_count#4HR",
    "ACTIVITY#IN_VEHICLE_duration#4HR",
    "ACTIVITY#IN_VEHICLE_proportion#4HR",
    "ACTIVITY#WALKING_count#4HR",
    "ACTIVITY#WALKING_duration#4HR",
    "ACTIVITY#WALKING_proportion#4HR",
    "ACTIVITY#STILL_count#4HR",
    "ACTIVITY#STILL_duration#4HR",
    "ACTIVITY#STILL_proportion#4HR",
    "STEP#count#4HR",
    "STEP#count2std#4HR",
    "SIGNIFICANT_MOTION#count#4HR",
    "SIGNIFICANT_MOTION#elapsed_time#4HR",
    "GRAVITY#X_mean#4HR",
    "GRAVITY#X_min#4HR",
    "GRAVITY#X_max#4HR",
    "GRAVITY#X_std#4HR",
    "GRAVITY#X_kurtosis#4HR",
    "GRAVITY#X_skewness#4HR",
    "GRAVITY#Y_mean#4HR",
    "GRAVITY#Y_min#4HR",
    "GRAVITY#Y_max#4HR",
    "GRAVITY#Y_std#4HR",
    "GRAVITY#Y_kurtosis#4HR",
    "GRAVITY#Y_skewness#4HR",
    "GRAVITY#Z_mean#4HR",
    "GRAVITY#Z_min#4HR",
    "GRAVITY#Z_max#4HR",
    "GRAVITY#Z_std#4HR",
    "GRAVITY#Z_kurtosis#4HR",
    "GRAVITY#Z_skewness#4HR",
    "LIGHT#count_0#4HR",
    "LIGHT#BRIGHTNESS_LOG_mean#4HR",
    "LIGHT#BRIGHTNESS_LOG_min#4HR",
    "LIGHT#BRIGHTNESS_LOG_max#4HR",
    "LIGHT#BRIGHTNESS_LOG_std#4HR",
    "LIGHT#BRIGHTNESS_LOG_kurtosis#4HR",
    "LIGHT#BRIGHTNESS_LOG_skewness#4HR",
    "APPUSAGE#entropy#4HR",
    "APPUSAGE#normalized_entropy#4HR",
    "APPUSAGE#COMMUNICATION#count#4HR",
    "APPUSAGE#COMMUNICATION#duration#4HR",
    "APPUSAGE#SOCIAL#count#4HR",
    "APPUSAGE#SOCIAL#duration#4HR",
    "APPUSAGE#HEALTH#count#4HR",
    "APPUSAGE#HEALTH#duration#4HR",
    "APPUSAGE#ENTERTAINMENT#count#4HR",
    "APPUSAGE#ENTERTAINMENT#duration#4HR",
    "APPUSAGE#LIFESTYLE#count#4HR",
    "APPUSAGE#LIFESTYLE#duration#4HR",
    "APPUSAGE#BOOKS#count#4HR",
    "APPUSAGE#BOOKS#duration#4HR",
    "APPUSAGE#VIDEO#count#4HR",
    "APPUSAGE#VIDEO#duration#4HR",
    "APPUSAGE#FINANCE#count#4HR",
    "APPUSAGE#FINANCE#duration#4HR",
    "APPUSAGE#PHOTOGRAPHY#count#4HR",
    "APPUSAGE#PHOTOGRAPHY#duration#4HR",
    "APPUSAGE#PRODUCTIVITY#count#4HR",
    "APPUSAGE#PRODUCTIVITY#duration#4HR",
    "CALL#count_ratio_in2missed#4HR",
    "CALL#count_ratio_in2out#4HR",
    "CALL#duration_ratio_in2out#4HR",
    "CALL#IN_duration#4HR",
    "CALL#OUT_duration#4HR",
    "CALL#MISSED_count#4HR",
    "CALL#IN_count#4HR",
    "CALL#OUT_count#4HR",
    #"EMA#sleep_trouble#4HR",
    #"EMA#poor_appetite#4HR",
    "KEYSTROKE#SOCIAL#backspace_ratio#4HR",
    "KEYSTROKE#SOCIAL#autocorrect_ratio#4HR",
    "KEYSTROKE#SOCIAL#autocorrect_accept_ratio#4HR",
    "KEYSTROKE#SOCIAL#count_sessions#4HR",
    "KEYSTROKE#SOCIAL#interkeyDelay#mean",
    "KEYSTROKE#NON-SOCIAL#backspace_ratio#4HR",
    "KEYSTROKE#NON-SOCIAL#autocorrect_ratio#4HR",
    "KEYSTROKE#NON-SOCIAL#autocorrect_accept_ratio#4HR",
    "KEYSTROKE#NON-SOCIAL#count_sessions#4HR",
    "KEYSTROKE#NON-SOCIAL#interkeyDelay#mean",
    "NOTIFICATIONS#SOCIAL#ARRIVED_count#4HR",
    "NOTIFICATIONS#SOCIAL#CLICKED_count#4HR",
    "NOTIFICATIONS#SOCIAL#DECISION_TIME_count#4HR",
    "NOTIFICATIONS#SOCIAL#DECISION_TIME_duration_in_sec",
    "NOTIFICATIONS#SOCIAL#count_ratio_clicked2arrived#4HR",
    "NOTIFICATIONS#SOCIAL#count_ratio_decided2arrived#4HR",
    "NOTIFICATIONS#NON-SOCIAL#ARRIVED_count#4HR",
    "NOTIFICATIONS#NON-SOCIAL#CLICKED_count#4HR",
    "NOTIFICATIONS#NON-SOCIAL#DECISION_TIME_count#4HR",
    "NOTIFICATIONS#NON-SOCIAL#DECISION_TIME_duration_in_sec",
    "NOTIFICATIONS#NON-SOCIAL#count_ratio_clicked2arrived#4HR",
    "NOTIFICATIONS#NON-SOCIAL#count_ratio_decided2arrived#4HR",
    "SCREEN_STATE#on_count#4HR",
    "SCREEN_STATE#off_count#4HR",
    "SCREEN_STATE#entropy#4HR",
    "SCREEN_STATE#normalized_entropy#4HR",
    "SCREEN_STATE#total_duration#4HR",
    "SCREEN_STATE#mean_duration#4HR",
    "SCREEN_STATE#check_count#4HR",
    "SOUND#ENERGY_mean#4HR",
    "SOUND#ENERGY_min#4HR",
    "SOUND#ENERGY_max#4HR",
    "SOUND#ENERGY_std#4HR",
    "SOUND#ENERGY_kurtosis#4HR",
    "SOUND#ENERGY_skewness#4HR",
    "TYPING#SOCIAL#count#4HR",
    "TYPING#SOCIAL#total#4HR",
    "TYPING#SOCIAL#mean#4HR",
    "TYPING#SOCIAL#std#4HR",
    "TYPING#SOCIAL#min#4HR",
    "TYPING#SOCIAL#max#4HR",
    "TYPING#SOCIAL#kurtosis#4HR",
    "TYPING#SOCIAL#skewness#4HR",
    "TYPING#NON-SOCIAL#count#4HR",
    "TYPING#NON-SOCIAL#total#4HR",
    "TYPING#NON-SOCIAL#mean#4HR",
    "TYPING#NON-SOCIAL#std#4HR",
    "TYPING#NON-SOCIAL#min#4HR",
    "TYPING#NON-SOCIAL#max#4HR",
    "TYPING#NON-SOCIAL#kurtosis#4HR",
    "TYPING#NON-SOCIAL#skewness#4HR",
    "UNLOCK_STATE#unlock_count#4HR",
    "UNLOCK_STATE#lock_count#4HR",
    "UNLOCK_STATE#entropy#4HR",
    "UNLOCK_STATE#normalized_entropy#4HR",
    "UNLOCK_STATE#total_duration#4HR",
    "UNLOCK_STATE#mean_duration#4HR",
  ]

  # feature_list_base: [
  #           "f_screen:phone_screen_rapids_avgdurationunlock",
  #           "f_screen:phone_screen_rapids_stddurationunlock",
  #           "f_screen:phone_screen_rapids_countepisodeunlock",
  #           "f_screen:phone_screen_rapids_sumdurationunlock",
  #           "f_slp:fitbit_sleep_intraday_rapids_maxdurationasleepunifiedmain",
  #           "f_slp:fitbit_sleep_intraday_rapids_countepisodeasleepunifiedmain",
  #           "f_slp:fitbit_sleep_intraday_rapids_countepisodeawakeunifiedmain",
  #           "f_slp:fitbit_sleep_intraday_rapids_ratiodurationasleepunifiedwithinmain",
  #           "f_slp:fitbit_sleep_intraday_rapids_sumdurationasleepunifiedmain",
  #           "f_slp:fitbit_sleep_intraday_rapids_sumdurationawakeunifiedmain",
  #           "f_steps:fitbit_steps_intraday_rapids_avgdurationactivebout",
  #           "f_steps:fitbit_steps_intraday_rapids_avgdurationsedentarybout",
  #           "f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout",
  #           "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout",
  #           "f_steps:fitbit_steps_intraday_rapids_sumsteps",
  #           "f_loc:phone_locations_barnett_circdnrtn",
  #           "f_loc:phone_locations_doryab_timeathome",
  #           "f_loc:phone_locations_doryab_locationentropy",
  #           "f_loc:phone_locations_doryab_loglocationvariance",
  #           "f_loc:phone_locations_doryab_avglengthstayatclusters",
  #           "f_loc:phone_locations_doryab_movingtostaticratio",
  #           "f_loc:phone_locations_doryab_numberlocationtransitions",
  #           "f_loc:phone_locations_doryab_numberofsignificantplaces",
  #           "f_loc:phone_locations_doryab_outlierstimepercent",
  #           "f_loc:phone_locations_doryab_radiusgyration",
  #           "f_loc:phone_locations_doryab_totaldistance",
  #           "f_loc:phone_locations_locmap_duration_in_locmap_study",
  #           "f_loc:phone_locations_locmap_percent_in_locmap_study",
  #           "f_loc:phone_locations_locmap_duration_in_locmap_exercise",
  #           "f_loc:phone_locations_locmap_percent_in_locmap_exercise",
  #           "f_loc:phone_locations_locmap_duration_in_locmap_greens",
  #           "f_loc:phone_locations_locmap_percent_in_locmap_greens",
  #       ]
  # feature_list_more_feat_types_base: [
  #           "f_screen:phone_screen_rapids_avgdurationunlock",
  #           "f_screen:phone_screen_rapids_stddurationunlock",
  #           "f_screen:phone_screen_rapids_countepisodeunlock",
  #           "f_screen:phone_screen_rapids_sumdurationunlock",
  #           "f_slp:fitbit_sleep_intraday_rapids_maxdurationasleepunifiedmain",
  #           "f_slp:fitbit_sleep_intraday_rapids_countepisodeasleepunifiedmain",
  #           "f_slp:fitbit_sleep_intraday_rapids_countepisodeawakeunifiedmain",
  #           "f_slp:fitbit_sleep_intraday_rapids_ratiodurationasleepunifiedwithinmain",
  #           "f_slp:fitbit_sleep_intraday_rapids_sumdurationasleepunifiedmain",
  #           "f_slp:fitbit_sleep_intraday_rapids_sumdurationawakeunifiedmain",
  #           "f_steps:fitbit_steps_intraday_rapids_avgdurationactivebout",
  #           "f_steps:fitbit_steps_intraday_rapids_avgdurationsedentarybout",
  #           "f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout",
  #           "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout",
  #           "f_steps:fitbit_steps_intraday_rapids_sumsteps",
  #           "f_loc:phone_locations_barnett_circdnrtn",
  #           "f_loc:phone_locations_doryab_timeathome",
  #           "f_loc:phone_locations_doryab_locationentropy",
  #           "f_loc:phone_locations_doryab_loglocationvariance",
  #           "f_loc:phone_locations_doryab_avglengthstayatclusters",
  #           "f_loc:phone_locations_doryab_movingtostaticratio",
  #           "f_loc:phone_locations_doryab_numberlocationtransitions",
  #           "f_loc:phone_locations_doryab_numberofsignificantplaces",
  #           "f_loc:phone_locations_doryab_outlierstimepercent",
  #           "f_loc:phone_locations_doryab_radiusgyration",
  #           "f_loc:phone_locations_doryab_totaldistance",
  #           "f_loc:phone_locations_locmap_duration_in_locmap_study",
  #           "f_loc:phone_locations_locmap_percent_in_locmap_study",
  #           "f_loc:phone_locations_locmap_duration_in_locmap_exercise",
  #           "f_loc:phone_locations_locmap_percent_in_locmap_exercise",
  #           "f_loc:phone_locations_locmap_duration_in_locmap_greens",
  #           "f_loc:phone_locations_locmap_percent_in_locmap_greens",
  #           "f_blue:phone_bluetooth_doryab_countscansmostfrequentdeviceacrossdatasetothers",
  #           "f_blue:phone_bluetooth_doryab_countscansmostfrequentdeviceacrossdatasetown",
  #           "f_blue:phone_bluetooth_doryab_meanscansothers",
  #           "f_blue:phone_bluetooth_doryab_meanscansown",
  #           "f_blue:phone_bluetooth_doryab_uniquedevicesothers",
  #           "f_blue:phone_bluetooth_doryab_uniquedevicesown",
  #           "f_call:phone_calls_rapids_incoming_count",
  #           "f_call:phone_calls_rapids_incoming_distinctcontacts",
  #           "f_call:phone_calls_rapids_incoming_sumduration",
  #           "f_call:phone_calls_rapids_missed_count",
  #           "f_call:phone_calls_rapids_outgoing_count",
  #           "f_call:phone_calls_rapids_outgoing_distinctcontacts",
  #           "f_call:phone_calls_rapids_outgoing_sumduration",
  #       ]

model_params:
  num_top_rule: 10 # number of top rules used for contextually filtered feature extraction
  # rule selection metric params
  metric_w1: 1.0
  metric_w2: 1.5
  metric_w3: 0.5

  # associate rule mining threshold
  arm_thresholds:
    weekday:
      morning:
        supp: 0.125
        conf: 0.125
      afternoon:
        supp: 0.125
        conf: 0.125
      evening:
        supp: 0.125
        conf: 0.125
      night:
        supp: 0.125
        conf: 0.125
    weekend:
      morning:
        supp: 0.125
        conf: 0.125
      afternoon:
        supp: 0.125
        conf: 0.125
      evening:
        supp: 0.125
        conf: 0.125
      night:
        supp: 0.125
        conf: 0.125

  # associate rule mining threshold
  # (higher than the normal params so that the number of rules can be controlled)
  arm_thresholds_memory_safe:
    weekday:
      morning:
        supp: 0.200
        conf: 0.200
      afternoon:
        supp: 0.200
        conf: 0.200
      evening:
        supp: 0.200
        conf: 0.200
      night:
        supp: 0.200
        conf: 0.200
    weekend:
      morning:
        supp: 0.200
        conf: 0.200
      afternoon:
        supp: 0.200
        conf: 0.200
      evening:
        supp: 0.200
        conf: 0.200
      night:
        supp: 0.200
        conf: 0.200

  arm_thresholds_memory_safer:
    weekday:
      morning:
        supp: 0.350
        conf: 0.350
      afternoon:
        supp: 0.350
        conf: 0.350
      evening:
        supp: 0.350
        conf: 0.350
      night:
        supp: 0.350
        conf: 0.350
    weekend:
      morning:
        supp: 0.350
        conf: 0.350
      afternoon:
        supp: 0.350
        conf: 0.350
      evening:
        supp: 0.350
        conf: 0.350
      night:
        supp: 0.350
        conf: 0.350

  arm_thresholds_memory_safest:
    weekday:
      morning:
        supp: 0.700
        conf: 0.700
      afternoon:
        supp: 0.700
        conf: 0.700
      evening:
        supp: 0.700
        conf: 0.700
      night:
        supp: 0.900
        conf: 0.900
    weekend:
      morning:
        supp: 0.800
        conf: 0.800
      afternoon:
        supp: 0.700
        conf: 0.700
      evening:
        supp: 0.700
        conf: 0.700
      night:
        supp: 0.900
        conf: 0.900


training_params:
  verbose: 2
  # whether to save and re-use features repetitively
  #     True only when re-running the exact same model training
  save_and_reload: False
