name: "ml_xu_interpretable"

feature_definition:
  use_norm_features: False # whether to use normalized features
  empty_feature_filtering_th: 0.5 # remove features based on a threshold -> for 0.5 remove data that has more than half  
  include_device_type: False # whether to include device type in the feature matrix
  # Feature used in the paper (a subset that is compatible within the dataset)

  feature_list_base: [
    "ACTIVITY#RUNNING_count",
    "ACTIVITY#RUNNING_duration",
    "ACTIVITY#RUNNING_proportion_count",
    "ACTIVITY#RUNNING_proportion_duration",
    "ACTIVITY#ON_BICYCLE_count",
    "ACTIVITY#ON_BICYCLE_duration",
    "ACTIVITY#ON_BICYCLE_proportion_count",
    "ACTIVITY#ON_BICYCLE_proportion_duration",
    "ACTIVITY#IN_VEHICLE_count",
    "ACTIVITY#IN_VEHICLE_duration",
    "ACTIVITY#IN_VEHICLE_proportion_count",
    "ACTIVITY#IN_VEHICLE_proportion_duration",
    "ACTIVITY#WALKING_count",
    "ACTIVITY#WALKING_duration",
    "ACTIVITY#WALKING_proportion_count",
    "ACTIVITY#WALKING_proportion_duration",
    "ACTIVITY#STILL_count",
    "ACTIVITY#STILL_duration",
    "ACTIVITY#STILL_proportion_count",
    "ACTIVITY#STILL_proportion_duration",
    
    "STEP#count",
    #"STEP#count2std",
    
    "SIGNIFICANT_MOTION#count",
    #"SIGNIFICANT_MOTION#elapsed_time",
    
    # "GRAVITY#X_mean",
    # "GRAVITY#X_min",
    # "GRAVITY#X_max",
    "GRAVITY#X_std",
    # "GRAVITY#X_kurtosis",
    # "GRAVITY#X_skewness",
    # "GRAVITY#Y_mean",
    # "GRAVITY#Y_min",
    # "GRAVITY#Y_max",
    "GRAVITY#Y_std",
    # "GRAVITY#Y_kurtosis",
    # "GRAVITY#Y_skewness",
    # "GRAVITY#Z_mean",
    # "GRAVITY#Z_min",
    # "GRAVITY#Z_max",
    "GRAVITY#Z_std",
    # "GRAVITY#Z_kurtosis",
    # "GRAVITY#Z_skewness",

    "LIGHT#count_0",
    "LIGHT#BRIGHTNESS_LOG_mean",
    # "LIGHT#BRIGHTNESS_LOG_min",
    # "LIGHT#BRIGHTNESS_LOG_max",
    "LIGHT#BRIGHTNESS_LOG_std",
    # "LIGHT#BRIGHTNESS_LOG_kurtosis",
    # "LIGHT#BRIGHTNESS_LOG_skewness",

    # "APPUSAGE#entropy",
    # "APPUSAGE#normalized_entropy",
    "APPUSAGE#COMMUNICATION_count",
    "APPUSAGE#COMMUNICATION_duration",
    "APPUSAGE#SOCIAL_count",
    "APPUSAGE#SOCIAL_duration",
    "APPUSAGE#NON-SOCIAL_count"
    "APPUSAGE#NON-SOCIAL_duration"
    # "APPUSAGE#HEALTH_count",
    # "APPUSAGE#HEALTH_duration",
    # "APPUSAGE#ENTERTAINMENT_count",
    # "APPUSAGE#ENTERTAINMENT_duration",
    # "APPUSAGE#LIFESTYLE_count",
    # "APPUSAGE#LIFESTYLE_duration",
    # "APPUSAGE#BOOKS_count",
    # "APPUSAGE#BOOKS_duration",
    # "APPUSAGE#VIDEO_count",
    # "APPUSAGE#VIDEO_duration",
    # "APPUSAGE#FINANCE_count",
    # "APPUSAGE#FINANCE_duration",
    # "APPUSAGE#PHOTOGRAPHY_count",
    # "APPUSAGE#PHOTOGRAPHY_duration",
    # "APPUSAGE#PRODUCTIVITY_count",
    # "APPUSAGE#PRODUCTIVITY_duration",
    
    "CALL#count_ratio_IN2all",
    "CALL#count_ratio_COUNT2all",
    "CALL#count_ratio_MISSED2all",
    "CALL#duration_ratio_in2out",
    "CALL#IN_duration",
    "CALL#OUT_duration",
    "CALL#MISSED_count",
    "CALL#IN_count",
    "CALL#OUT_count",

    # "EMA#sleep_trouble",
    # "EMA#poor_appetite",

    "KEYSTROKE#SOCIAL_backspace_ratio",
    "KEYSTROKE#SOCIAL_autocorrect_ratio",
    "KEYSTROKE#SOCIAL_autocorrect_accept_ratio",
    "KEYSTROKE#SOCIAL_count_sessions",
    "KEYSTROKE#SOCIAL_mean_duration_sessions",
    "KEYSTROKE#SOCIAL_interkeyDelay_mean",
    "KEYSTROKE#NON-SOCIAL_backspace_ratio",
    "KEYSTROKE#NON-SOCIAL_autocorrect_ratio",
    "KEYSTROKE#NON-SOCIAL_autocorrect_accept_ratio",
    "KEYSTROKE#NON-SOCIAL_count_sessions",
    "KEYSTROKE#NON-SOCIAL_interkeyDelay_mean",

    ### Notifications separated in social & non-social
    "NOTIFICATIONS#SOCIAL_ARRIVED_count",
    "NOTIFICATIONS#SOCIAL_CLICKED_count",
    "NOTIFICATIONS#SOCIAL_DECISION_TIME_count",
    "NOTIFICATIONS#SOCIAL_DECISION_TIME_MeanDuration",
    "NOTIFICATIONS#SOCIAL_count_ratio_clicked2arrived",
    "NOTIFICATIONS#SOCIAL_count_ratio_decided2arrived",
    "NOTIFICATIONS#NON-SOCIAL_ARRIVED_count",
    "NOTIFICATIONS#NON-SOCIAL_CLICKED_count",
    "NOTIFICATIONS#NON-SOCIAL_DECISION_TIME_count",
    "NOTIFICATIONS#NON-SOCIAL_DECISION_TIME_duration_in_sec",
    "NOTIFICATIONS#NON-SOCIAL_count_ratio_clicked2arrived",
    # "NOTIFICATIONS#NON-SOCIAL_count_ratio_decided2arrived",

    "SCREEN_STATE#on_count",
    # "SCREEN_STATE#off_count",
    # "SCREEN_STATE#entropy",
    # "SCREEN_STATE#normalized_entropy",
    "SCREEN_STATE#total_duration",
    # "SCREEN_STATE#mean_duration",
    "SCREEN_STATE#check_count",

    "SOUND#ENERGY_mean",
    # "SOUND#ENERGY_min",
    # "SOUND#ENERGY_max",
    "SOUND#ENERGY_std",
    # "SOUND#ENERGY_kurtosis",
    # "SOUND#ENERGY_skewness",

    "TYPING#SOCIAL_count",
    "TYPING#SOCIAL_total",
    # "TYPING#SOCIAL_mean",
    # "TYPING#SOCIAL_std",
    # "TYPING#SOCIAL_min",
    # "TYPING#SOCIAL_max",
    # "TYPING#SOCIAL_kurtosis",
    # "TYPING#SOCIAL_skewness",
    "TYPING#NON-SOCIAL_count",
    "TYPING#NON-SOCIAL_total",
    # "TYPING#NON-SOCIAL_mean",
    # "TYPING#NON-SOCIAL_std",
    # "TYPING#NON-SOCIAL_min",
    # "TYPING#NON-SOCIAL_max",
    # "TYPING#NON-SOCIAL_kurtosis",
    # "TYPING#NON-SOCIAL_skewness",

    "UNLOCK_STATE#unlock_count",
    # "UNLOCK_STATE#lock_count",
    # "UNLOCK_STATE#entropy",
    # "UNLOCK_STATE#normalized_entropy",
    "UNLOCK_STATE#total_duration",
    # "UNLOCK_STATE#mean_duration",
  ]

  feature_list_more_feat_types_base: [
    "ACTIVITY#RUNNING_count",
    "ACTIVITY#RUNNING_duration",
    "ACTIVITY#RUNNING_proportion",
    "ACTIVITY#ON_BICYCLE_count",
    "ACTIVITY#ON_BICYCLE_duration",
    "ACTIVITY#ON_BICYCLE_proportion",
    "ACTIVITY#IN_VEHICLE_count",
    "ACTIVITY#IN_VEHICLE_duration",
    "ACTIVITY#IN_VEHICLE_proportion",
    "ACTIVITY#WALKING_count",
    "ACTIVITY#WALKING_duration",
    "ACTIVITY#WALKING_proportion",
    "ACTIVITY#STILL_count",
    "ACTIVITY#STILL_duration",
    "ACTIVITY#STILL_proportion",

    "STEP#count",
    # "STEP#count2std",
    
    "SIGNIFICANT_MOTION#count",
    # "SIGNIFICANT_MOTION#elapsed_time",
    
    # "GRAVITY#X_mean",
    # "GRAVITY#X_min",
    # "GRAVITY#X_max",
    "GRAVITY#X_std",
    # "GRAVITY#X_kurtosis",
    # "GRAVITY#X_skewness",
    # "GRAVITY#Y_mean",
    # "GRAVITY#Y_min",
    # "GRAVITY#Y_max",
    "GRAVITY#Y_std",
    # "GRAVITY#Y_kurtosis",
    # "GRAVITY#Y_skewness",
    # "GRAVITY#Z_mean",
    # "GRAVITY#Z_min",
    # "GRAVITY#Z_max",
    "GRAVITY#Z_std",
    # "GRAVITY#Z_kurtosis",
    # "GRAVITY#Z_skewness",
    
    "LIGHT#count_0",
    "LIGHT#BRIGHTNESS_LOG_mean",
    # "LIGHT#BRIGHTNESS_LOG_min",
    # "LIGHT#BRIGHTNESS_LOG_max",
    "LIGHT#BRIGHTNESS_LOG_std",
    # "LIGHT#BRIGHTNESS_LOG_kurtosis",
    # "LIGHT#BRIGHTNESS_LOG_skewness",
    
    # "APPUSAGE#entropy",
    # "APPUSAGE#normalized_entropy",
    "APPUSAGE#COMMUNICATION#count",
    "APPUSAGE#COMMUNICATION#duration",
    "APPUSAGE#SOCIAL#count",
    "APPUSAGE#SOCIAL#duration",
    "APPUSAGE#HEALTH#count",
    "APPUSAGE#HEALTH#duration",
    "APPUSAGE#ENTERTAINMENT#count",
    "APPUSAGE#ENTERTAINMENT#duration",
    "APPUSAGE#LIFESTYLE#count",
    "APPUSAGE#LIFESTYLE#duration",
    "APPUSAGE#BOOKS#count",
    "APPUSAGE#BOOKS#duration",
    "APPUSAGE#VIDEO#count",
    "APPUSAGE#VIDEO#duration",
    "APPUSAGE#FINANCE#count",
    "APPUSAGE#FINANCE#duration",
    "APPUSAGE#PHOTOGRAPHY#count",
    "APPUSAGE#PHOTOGRAPHY#duration",
    "APPUSAGE#PRODUCTIVITY#count",
    "APPUSAGE#PRODUCTIVITY#duration",
    
    "CALL#count_ratio_in2missed",
    "CALL#count_ratio_in2out",
    "CALL#duration_ratio_in2out",
    "CALL#IN_duration",
    "CALL#OUT_duration",
    "CALL#MISSED_count",
    "CALL#IN_count",
    "CALL#OUT_count",
    
    #"EMA#sleep_trouble",
    #"EMA#poor_appetite",
    
    "KEYSTROKE#SOCIAL#backspace_ratio",
    "KEYSTROKE#SOCIAL#autocorrect_ratio",
    "KEYSTROKE#SOCIAL#autocorrect_accept_ratio",
    "KEYSTROKE#SOCIAL#count_sessions",
    "KEYSTROKE#SOCIAL#interkeyDelay_mean",
    "KEYSTROKE#NON-SOCIAL#backspace_ratio",
    "KEYSTROKE#NON-SOCIAL#autocorrect_ratio",
    "KEYSTROKE#NON-SOCIAL#autocorrect_accept_ratio",
    "KEYSTROKE#NON-SOCIAL#count_sessions",
    "KEYSTROKE#NON-SOCIAL#interkeyDelay_mean",
    
    "NOTIFICATIONS#SOCIAL#ARRIVED_count",
    "NOTIFICATIONS#SOCIAL#CLICKED_count",
    "NOTIFICATIONS#SOCIAL#DECISION_TIME_count",
    "NOTIFICATIONS#SOCIAL#DECISION_TIME_duration_in_sec",
    "NOTIFICATIONS#SOCIAL#count_ratio_clicked2arrived",
    "NOTIFICATIONS#SOCIAL#count_ratio_decided2arrived",
    "NOTIFICATIONS#NON-SOCIAL#ARRIVED_count",
    "NOTIFICATIONS#NON-SOCIAL#CLICKED_count",
    "NOTIFICATIONS#NON-SOCIAL#DECISION_TIME_count",
    "NOTIFICATIONS#NON-SOCIAL#DECISION_TIME_duration_in_sec",
    "NOTIFICATIONS#NON-SOCIAL#count_ratio_clicked2arrived",
    "NOTIFICATIONS#NON-SOCIAL#count_ratio_decided2arrived",
    
    "SCREEN_STATE#on_count",
    # "SCREEN_STATE#off_count",
    # "SCREEN_STATE#entropy",
    # "SCREEN_STATE#normalized_entropy",
    "SCREEN_STATE#total_duration",
    # "SCREEN_STATE#mean_duration",
    "SCREEN_STATE#check_count",
    
    "SOUND#ENERGY_mean",
    # "SOUND#ENERGY_min",
    # "SOUND#ENERGY_max",
    "SOUND#ENERGY_std",
    # "SOUND#ENERGY_kurtosis",
    # "SOUND#ENERGY_skewness",
    
    "TYPING#SOCIAL#count",
    "TYPING#SOCIAL#total",
    # "TYPING#SOCIAL#mean",
    # "TYPING#SOCIAL#std",
    # "TYPING#SOCIAL#min",
    # "TYPING#SOCIAL#max",
    # "TYPING#SOCIAL#kurtosis",
    # "TYPING#SOCIAL#skewness",
    "TYPING#NON-SOCIAL#count",
    "TYPING#NON-SOCIAL#total",
    # "TYPING#NON-SOCIAL#mean",
    # "TYPING#NON-SOCIAL#std",
    # "TYPING#NON-SOCIAL#min",
    # "TYPING#NON-SOCIAL#max",
    # "TYPING#NON-SOCIAL#kurtosis",
    # "TYPING#NON-SOCIAL#skewness",
    
    "UNLOCK_STATE#unlock_count",
    # "UNLOCK_STATE#lock_count",
    # "UNLOCK_STATE#entropy",
    "UNLOCK_STATE#normalized_entropy",
    # "UNLOCK_STATE#total_duration",
    # "UNLOCK_STATE#mean_duration",
  ]

  # feature_list_base: [
        #     "f_screen:phone_screen_rapids_avgdurationunlock",
        #     "f_screen:phone_screen_rapids_stddurationunlock",
        #     "f_screen:phone_screen_rapids_countepisodeunlock",
        #     "f_screen:phone_screen_rapids_sumdurationunlock",
        #     "f_slp:fitbit_sleep_intraday_rapids_maxdurationasleepunifiedmain",
        #     "f_slp:fitbit_sleep_intraday_rapids_countepisodeasleepunifiedmain",
        #     "f_slp:fitbit_sleep_intraday_rapids_countepisodeawakeunifiedmain",
        #     "f_slp:fitbit_sleep_intraday_rapids_ratiodurationasleepunifiedwithinmain",
        #     "f_slp:fitbit_sleep_intraday_rapids_sumdurationasleepunifiedmain",
        #     "f_slp:fitbit_sleep_intraday_rapids_sumdurationawakeunifiedmain",
        #     "f_steps:fitbit_steps_intraday_rapids_avgdurationactivebout",
        #     "f_steps:fitbit_steps_intraday_rapids_avgdurationsedentarybout",
        #     "f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout",
        #     "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout",
        #     "f_steps:fitbit_steps_intraday_rapids_sumsteps",
        #     "f_loc:phone_locations_barnett_circdnrtn",
        #     "f_loc:phone_locations_doryab_timeathome",
        #     "f_loc:phone_locations_doryab_locationentropy",
        #     "f_loc:phone_locations_doryab_loglocationvariance",
        #     "f_loc:phone_locations_doryab_avglengthstayatclusters",
        #     "f_loc:phone_locations_doryab_movingtostaticratio",
        #     "f_loc:phone_locations_doryab_numberlocationtransitions",
        #     "f_loc:phone_locations_doryab_numberofsignificantplaces",
        #     "f_loc:phone_locations_doryab_outlierstimepercent",
        #     "f_loc:phone_locations_doryab_radiusgyration",
        #     "f_loc:phone_locations_doryab_totaldistance",
        #     "f_loc:phone_locations_locmap_duration_in_locmap_study",
        #     "f_loc:phone_locations_locmap_percent_in_locmap_study",
        #     "f_loc:phone_locations_locmap_duration_in_locmap_exercise",
        #     "f_loc:phone_locations_locmap_percent_in_locmap_exercise",
        #     "f_loc:phone_locations_locmap_duration_in_locmap_greens",
        #     "f_loc:phone_locations_locmap_percent_in_locmap_greens",
        # ]

  # feature_list_more_feat_types_base: [
  #           "f_screen:phone_screen_rapids_avgdurationunlock",
  #           "f_screen:phone_screen_rapids_stddurationunlock",
  #           "f_screen:phone_screen_rapids_countepisodeunlock",
  #           "f_screen:phone_screen_rapids_sumdurationunlock",
  #           "f_slp:fitbit_sleep_intraday_rapids_maxdurationasleepunifiedmain",
  #           "f_slp:fitbit_sleep_intraday_rapids_countepisodeasleepunifiedmain",
  #           "f_slp:fitbit_sleep_intraday_rapids_countepisodeawakeunifiedmain",
  #           "f_slp:fitbit_sleep_intraday_rapids_ratiodurationasleepunifiedwithinmain",
  #           "f_slp:fitbit_sleep_intraday_rapids_sumdurationasleepunifiedmain",
  #           "f_slp:fitbit_sleep_intraday_rapids_sumdurationawakeunifiedmain",
  #           "f_steps:fitbit_steps_intraday_rapids_avgdurationactivebout",
  #           "f_steps:fitbit_steps_intraday_rapids_avgdurationsedentarybout",
  #           "f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout",
  #           "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout",
  #           "f_steps:fitbit_steps_intraday_rapids_sumsteps",
  #           "f_loc:phone_locations_barnett_circdnrtn",
  #           "f_loc:phone_locations_doryab_timeathome",
  #           "f_loc:phone_locations_doryab_locationentropy",
  #           "f_loc:phone_locations_doryab_loglocationvariance",
  #           "f_loc:phone_locations_doryab_avglengthstayatclusters",
  #           "f_loc:phone_locations_doryab_movingtostaticratio",
  #           "f_loc:phone_locations_doryab_numberlocationtransitions",
  #           "f_loc:phone_locations_doryab_numberofsignificantplaces",
  #           "f_loc:phone_locations_doryab_outlierstimepercent",
  #           "f_loc:phone_locations_doryab_radiusgyration",
  #           "f_loc:phone_locations_doryab_totaldistance",
  #           "f_loc:phone_locations_locmap_duration_in_locmap_study",
  #           "f_loc:phone_locations_locmap_percent_in_locmap_study",
  #           "f_loc:phone_locations_locmap_duration_in_locmap_exercise",
  #           "f_loc:phone_locations_locmap_percent_in_locmap_exercise",
  #           "f_loc:phone_locations_locmap_duration_in_locmap_greens",
  #           "f_loc:phone_locations_locmap_percent_in_locmap_greens",
  #           "f_blue:phone_bluetooth_doryab_countscansmostfrequentdeviceacrossdatasetothers",
  #           "f_blue:phone_bluetooth_doryab_countscansmostfrequentdeviceacrossdatasetown",
  #           "f_blue:phone_bluetooth_doryab_meanscansothers",
  #           "f_blue:phone_bluetooth_doryab_meanscansown",
  #           "f_blue:phone_bluetooth_doryab_uniquedevicesothers",
  #           "f_blue:phone_bluetooth_doryab_uniquedevicesown",
  #           "f_call:phone_calls_rapids_incoming_count",
  #           "f_call:phone_calls_rapids_incoming_distinctcontacts",
  #           "f_call:phone_calls_rapids_incoming_sumduration",
  #           "f_call:phone_calls_rapids_missed_count",
  #           "f_call:phone_calls_rapids_outgoing_count",
  #           "f_call:phone_calls_rapids_outgoing_distinctcontacts",
  #           "f_call:phone_calls_rapids_outgoing_sumduration",
  #       ]

model_params:
  num_top_rule: 10 # number of top rules used for contextually filtered feature extraction
  # rule selection metric params
  metric_w1: 1.0
  metric_w2: 1.5
  metric_w3: 0.5

  # associate rule mining threshold
  arm_thresholds:
    weekday:
      morning:
        supp: 0.125
        conf: 0.125
      afternoon:
        supp: 0.125
        conf: 0.125
      evening:
        supp: 0.125
        conf: 0.125
      night:
        supp: 0.125
        conf: 0.125
    weekend:
      morning:
        supp: 0.125
        conf: 0.125
      afternoon:
        supp: 0.125
        conf: 0.125
      evening:
        supp: 0.125
        conf: 0.125
      night:
        supp: 0.125
        conf: 0.125

  # associate rule mining threshold
  # (higher than the normal params so that the number of rules can be controlled)
  arm_thresholds_memory_safe:
    weekday:
      morning:
        supp: 0.200
        conf: 0.200
      afternoon:
        supp: 0.200
        conf: 0.200
      evening:
        supp: 0.200
        conf: 0.200
      night:
        supp: 0.200
        conf: 0.200
    weekend:
      morning:
        supp: 0.200
        conf: 0.200
      afternoon:
        supp: 0.200
        conf: 0.200
      evening:
        supp: 0.200
        conf: 0.200
      night:
        supp: 0.200
        conf: 0.200

  arm_thresholds_memory_safer:
    weekday:
      morning:
        supp: 0.350
        conf: 0.350
      afternoon:
        supp: 0.350
        conf: 0.350
      evening:
        supp: 0.350
        conf: 0.350
      night:
        supp: 0.350
        conf: 0.350
    weekend:
      morning:
        supp: 0.350
        conf: 0.350
      afternoon:
        supp: 0.350
        conf: 0.350
      evening:
        supp: 0.350
        conf: 0.350
      night:
        supp: 0.350
        conf: 0.350

  arm_thresholds_memory_safest:
    weekday:
      morning:
        supp: 0.700
        conf: 0.700
      afternoon:
        supp: 0.700
        conf: 0.700
      evening:
        supp: 0.700
        conf: 0.700
      night:
        supp: 0.900
        conf: 0.900
    weekend:
      morning:
        supp: 0.800
        conf: 0.800
      afternoon:
        supp: 0.700
        conf: 0.700
      evening:
        supp: 0.700
        conf: 0.700
      night:
        supp: 0.900
        conf: 0.900


training_params:
  verbose: 1
  # whether to save and re-use features repetitively
  #     True only when re-running the exact same model training
  save_and_reload: False
